<template>
  <div class="d-flex items-center justify-center">
    <div class="loadingio-spinner-spinner-j3org2m3bp"><div class="ldio-lnno0dypj7r"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div></div>
  </div>
</template>

<style scoped>
/* loader */
@keyframes ldio-lnno0dypj7r {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-lnno0dypj7r div {
  left: 77.08px;
  top: 39.36px;
  position: absolute;
  animation: ldio-lnno0dypj7r linear 1.5384615384615383s infinite;
  background: #ff6464;
  width: 9.84px;
  height: 19.68px;
  border-radius: 1.5743999999999998px / 1.5743999999999998px;
  transform-origin: 4.92px 42.64px;
}.ldio-lnno0dypj7r div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -1.4102564102564101s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -1.282051282051282s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -1.1538461538461537s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -1.0256410256410255s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.8974358974358974s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.7692307692307692s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.641025641025641s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.5128205128205128s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.3846153846153846s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.2564102564102564s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.1282051282051282s;
  background: #ff6464;
}.ldio-lnno0dypj7r div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #ff6464;
}
.loadingio-spinner-spinner-j3org2m3bp {
  width: 164px;
  height: 164px;
  display: inline-block;
  overflow: hidden;
  background: rgba(255, 255, 255, 0);
}
.ldio-lnno0dypj7r {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-lnno0dypj7r div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>